name: vagabond # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Vagabond and cluster4x crystallographic software package
description: |
  Vagabond and cluster4x are crystallographic tools for refining protein
  structures and clustering datasets, respectively.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
